version: '3.9'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false

    volumes:
    - data:/usr/share/elasticsearch/data

    ports:
      - 9200:9200

    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:8.14.2
    container_name: kib01
    environment:
      - node.name=kib01
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://es01:9200

    ports:
      - 5601:5601

    networks:
      - elastic
    depends_on:
      - es01

volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge
